# Auth
POST {{Host}}/Auth/Login
accept: text/plain
Content-Type: application/json

{
  "usernameOrEmail": "Tobbe3108",
  "password": "Zxasqw12"
}

> {% 
client.global.set("auth_token", response.body);
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###